default: &default
  adapter: postgresql
  encoding: unicode
  pool: 25
  timeout: 5000
  
development:
  <<: *default
  url: <%= ENV['DATABASE_URL'] || 'postgres://postgres:postgres@localhost:5432/controle_km_development' %>
  database: controle_km_development

test:
  <<: *default
  url: <%= ENV['DATABASE_URL'] || 'postgres://postgres:postgres@localhost:5432/controle_km_test' %>
  database: controle_km_test


production:
  database: solutis-km_production
  username: solutis-km
  password: <%= ENV['SOLUTIS-KM_DATABASE_PASSWORD'] %>
